version: "3.8"

services:
  backend:
    build:
      context: .
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app/backend # Only mount the source codes:
    # ports:
    #   - "8000:8000"
    networks:
      - app-network

  iris:
    image: intersystemsdc/iris-community:latest
    container_name: iris-comm
    ports:
      - "1972:1972"
      - "52773:52773"
    environment:
      - IRIS_PASSWORD=demo
      - IRIS_USERNAME=demo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    # ports:
    #   - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
