version: '3.8'

services:
  web:
    build:
      context: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - iris

  iris:
    image: intersystemsdc/iris-community:latest
    container_name: iris-comm
    ports:
      - "1972:1972"
      - "52773:52773"
    environment:
      - IRIS_PASSWORD=demo
      - IRIS_USERNAME=demo
