version: '3.8'

services:
  web:
    build:
      context: .
    command: poetry run uvicorn backend.app:app_instance --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      # depends_on:
      #   - redis

      # redis:
      #   image: redis:latest
      #   ports:
      #     - "6379:6379"
